version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  diplodocus-harder.cyrhades.fr:
    image: anssi/fcsc2022-reverse-diplodocus-harder:latest
    ports:
      - ${PORT_SSH}:4000